# Generated by Django 5.2.6 on 2025-12-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', max_length=50),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
